/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_h2r_jSolver */

#ifndef _Included_edu_h2r_jSolver
#define _Included_edu_h2r_jSolver
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_h2r_jSolver
 * Method:    train
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_edu_h2r_jSolver_train
  (JNIEnv *, jobject);

/*
 * Class:     edu_h2r_jSolver
 * Method:    getNetPointer
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_edu_h2r_jSolver_getNetPointer
  (JNIEnv *, jobject);

/*
 * Class:     edu_h2r_jSolver
 * Method:    createSolver
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_edu_h2r_jSolver_createSolver
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
