/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_h2r_jNet */

#ifndef _Included_edu_h2r_jNet
#define _Included_edu_h2r_jNet
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_h2r_jNet
 * Method:    createNet
 * Signature: (Ljava/lang/String;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_edu_h2r_jNet_createNet__Ljava_lang_String_2Ljava_lang_String_2
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     edu_h2r_jNet
 * Method:    createNet
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_edu_h2r_jNet_createNet__Ljava_lang_String_2
  (JNIEnv *, jobject, jstring);

/*
 * Class:     edu_h2r_jNet
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_edu_h2r_jNet_dispose
  (JNIEnv *, jobject);

/*
 * Class:     edu_h2r_jNet
 * Method:    forwardTo
 * Signature: ([FLjava/lang/String;)[F
 */
JNIEXPORT jfloatArray JNICALL Java_edu_h2r_jNet_forwardTo
  (JNIEnv *, jobject, jfloatArray, jstring);

/*
 * Class:     edu_h2r_jNet
 * Method:    setMemoryDataLayer
 * Signature: (Ljava/lang/String;[F[F)V
 */
JNIEXPORT void JNICALL Java_edu_h2r_jNet_setMemoryDataLayer
  (JNIEnv *, jobject, jstring, jfloatArray, jfloatArray);

/*
 * Class:     edu_h2r_jNet
 * Method:    getLayerNames
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_edu_h2r_jNet_getLayerNames
  (JNIEnv *, jobject);

/*
 * Class:     edu_h2r_jNet
 * Method:    getNodeCount
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_edu_h2r_jNet_getNodeCount
  (JNIEnv *, jobject, jstring);

/*
 * Class:     edu_h2r_jNet
 * Method:    getInputHeight
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_edu_h2r_jNet_getInputHeight
  (JNIEnv *, jobject);

/*
 * Class:     edu_h2r_jNet
 * Method:    getInputWidth
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_edu_h2r_jNet_getInputWidth
  (JNIEnv *, jobject);

/*
 * Class:     edu_h2r_jNet
 * Method:    hasLayer
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_edu_h2r_jNet_hasLayer
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
